name: Terraform Deploy
on: 
  push:
    branches: ["master"]
env:
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
  TF_VAR_bucket_name: ${{secrets.BUCKET_NAME}}


jobs:
  init-and-validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps: 
      - name: Checkout
        uses: actions/checkout@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

  plan:
    runs-on: ubuntu-latest
    needs: init-and-validate     
    steps:
     - name: Checkout
       uses: actions/checkout@v3

     - name: Terraform Plan
       run: terraform plan -out=plan.out

     - name: Publish Artifact
       uses: actions/upload-artifact@v3
       with:
        name: plan-out
        path: './plan.out'

  apply:
    runs-on: ubuntu-latest
    environment: 'apply-destroy'
    needs: [init-and-validate, plan]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: plan-out
          path: './plan.out'

      - name: Terraform Apply
        run: terraform apply

  destroy:
    runs-on: ubuntu-latest
    environment: 'apply-destroy'
    needs: [init-and-validate, plan, apply]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Terraform Destroy
        run: terraform destroy -auto-approve        






